create database schema
LottiL/access-control-system pull request #1
Opened 2024-06-27 09:55 UTC by LottiL

2024-06-29 09:36 UTC, szemate requested changes
Jók lettek a változtatások, akartam is javasolni, hogy legyen külön `pass` és `passType` :)

Amin változtatnék:
- legyen egységesen egyesszámban vagy többesszámban a táblák neve (jelenleg van `pass` és `users`)
- legyen egységes a camelCase vagy snake_case használata (jelenleg van `pass_type` és `gymName`)
- szerintem érdemes a táblákra úgy gondolni, mint osztályokra, amikor elnevezed az oszlopokat, pl. `gymName.gymName` helyett `gym.name` jobb lenne, `passType.pass_type` helyett `passType.name`, staff.staffName` helyett `staff.name`, `passes.passNumber` helyett `pass.number`
- szerintem a `users` és a `staff` táblákat össze lehetne vonni, és lehetne egy külön `passwords` tábla `passwordSalt`, `passwordHash` és `userId` oszlopokkal, így egységesen lehetne kezelni minden típusú felhasználót

2024-06-29 09:58 UTC, szemate commented on database/db.sql
> +    passID INT NOT NULL,
Ez a `passID` miben különbözik az `id`-tól?

2024-06-29 11:36 UTC, LottiL commented on database/db.sql
> +    passID INT NOT NULL,
A passID-t igazából cardNumbernek gondoltam, azért nem az id-t hagytam, mert így ha vki leadja a bérletet, még kiadható másnak.

2024-06-29 11:51 UTC, LottiL commented on database/db.sql
> +    passID INT NOT NULL,
"szerintem érdemes a táblákra úgy gondolni, mint osztályokra, amikor elnevezed az oszlopokat, pl. gymName.gymName helyett gym.name jobb lenne, passType.pass_type helyett passType.name, staff.staffName helyett staff.name, passes.passNumber helyett pass.number"
A "name" bekékül, mint az SQL kulcsszavai, ezért nem akartam azt használni. De értem a problémát, javítom :)

2024-06-30 15:25 UTC, szemate approved these changes
Tök jó! Nyilván lehet utólag is változtatni, ha kiderül, hogy kimaradt valami

2024-07-02 07:33 UTC, merged